spring:
  application:
    name: board_validation
  config:
    use-legacy-processing: true
  profiles:
    active:
      - localhost
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  datasource:
    db:
      hikari:
        driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
        jdbc-url: jdbc:log4jdbc:mariadb://3307/shelter
        username: root
        password: 3828
        auto-commit: false
        connection-test-query: SELECT 1
        maximum-pool-size: 10
        transaction-isolation: TRANSACTION_READ_UNCOMMITTED
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 10MB
      location: ${java.io.tmpdir}
      max-file-size: 1024MB
      max-request-size: 1024MB
  thymeleaf:
    mode: HTML
    encoding: UTF-8
    prefix: classpath:/templates/
    suffix: .html
    cache: false
    check-template-location: true
  messages:
    basename: classpath:messages/message
    encoding: UTF-8
    cache-duration: -1
    always-use-message-format: false
    fallback-to-system-locale: true
    use-code-as-default-message: false
server:
  port: 8889
  servlet:
    context-path: /
    session:
      timeout: 86400 # 24시간 설정
      tracking-modes: cookie
  error:
    whitelabel:
      enabled: false
    include-exception: true
    include-stacktrace: always
    path: /common/error
logging:
  config: classpath:logback-spring.xml
upload:
  root: /home/ini-home2022/upload
path:

  editor: /editor
  image: /image
  static: /static
  res: /res

log:
  path: /server/ini-home/logs
app:
  site:
    url: localhost:8891
  email:
    info: initech@kpic.re.kr
---
spring:
  profiles:
    - localhost
upload:
  root: C://@/ini-home2022/upload
log:
  path: C://@/ini-home2022/log

---
spring:
  profiles:
    - development
app:
  site:
    url: initech.iooo.pw

---
